#!/bin/bash

function createrr() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/rr.isfcr.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/rr.isfcr.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-rr --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-rr.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-rr.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-rr.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-rr.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/rr.isfcr.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy rr's CA cert to rr's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/rr.isfcr.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/rr/ca-cert.pem" "${PWD}/organizations/peerOrganizations/rr.isfcr.com/msp/tlscacerts/ca.crt"

  # Copy rr's CA cert to rr's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/rr.isfcr.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/rr/ca-cert.pem" "${PWD}/organizations/peerOrganizations/rr.isfcr.com/tlsca/tlsca.rr.isfcr.com-cert.pem"

  # Copy rr's CA cert to rr's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/rr.isfcr.com/ca"
  cp "${PWD}/organizations/fabric-ca/rr/ca-cert.pem" "${PWD}/organizations/peerOrganizations/rr.isfcr.com/ca/ca.rr.isfcr.com-cert.pem"

# Peer Registration ---------------------------------------
  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-rr --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  #This is thr new peers that are getting registered into the network
  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-rr --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering peer2"
  set -x
  fabric-ca-client register --caname ca-rr --id.name peer2 --id.secret peer2pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

#---------------------------------------------
  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-rr --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-rr --id.name rradmin --id.secret rradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-rr -M "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer0.rr.isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer0.rr.isfcr.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-rr -M "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer0.rr.isfcr.com/tls" --enrollment.profile tls --csr.hosts peer0.rr.isfcr.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer0.rr.isfcr.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer0.rr.isfcr.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer0.rr.isfcr.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer0.rr.isfcr.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer0.rr.isfcr.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer0.rr.isfcr.com/tls/server.key"


  infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-rr -M "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer1.rr.isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer1.rr.isfcr.com/msp/config.yaml"

  infoln "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-rr -M "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer1.rr.isfcr.com/tls" --enrollment.profile tls --csr.hosts peer1.rr.isfcr.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer1.rr.isfcr.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer1.rr.isfcr.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer1.rr.isfcr.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer1.rr.isfcr.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer1.rr.isfcr.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer1.rr.isfcr.com/tls/server.key"
  
  
  infoln "Generating the peer2 msp"
  set -x
  fabric-ca-client enroll -u https://peer2:peer2pw@localhost:7054 --caname ca-rr -M "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer2.rr.isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer2.rr.isfcr.com/msp/config.yaml"

  infoln "Generating the peer2-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer2:peer2pw@localhost:7054 --caname ca-rr -M "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer2.rr.isfcr.com/tls" --enrollment.profile tls --csr.hosts peer2.rr.isfcr.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer2.rr.isfcr.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer2.rr.isfcr.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer2.rr.isfcr.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer2.rr.isfcr.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer2.rr.isfcr.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/rr.isfcr.com/peers/peer2.rr.isfcr.com/tls/server.key"
  
  
  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-rr -M "${PWD}/organizations/peerOrganizations/rr.isfcr.com/users/User1@rr.isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/rr.isfcr.com/users/User1@rr.isfcr.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://rradmin:rradminpw@localhost:7054 --caname ca-rr -M "${PWD}/organizations/peerOrganizations/rr.isfcr.com/users/Admin@rr.isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/rr/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/rr.isfcr.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/rr.isfcr.com/users/Admin@rr.isfcr.com/msp/config.yaml"
}



function createec() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/ec.isfcr.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/ec.isfcr.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-ec --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-ec.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-ec.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-ec.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-ec.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/ec.isfcr.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy ec's CA cert to ec's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/ec.isfcr.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ec/ca-cert.pem" "${PWD}/organizations/peerOrganizations/ec.isfcr.com/msp/tlscacerts/ca.crt"

  # Copy ec's CA cert to ec's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/ec.isfcr.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ec/ca-cert.pem" "${PWD}/organizations/peerOrganizations/ec.isfcr.com/tlsca/tlsca.ec.isfcr.com-cert.pem"

  # Copy ec's CA cert to ec's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/ec.isfcr.com/ca"
  cp "${PWD}/organizations/fabric-ca/ec/ca-cert.pem" "${PWD}/organizations/peerOrganizations/ec.isfcr.com/ca/ca.ec.isfcr.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-ec --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-ec --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null


  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-ec --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-ec --id.name ecadmin --id.secret ecadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-ec -M "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer0.ec.isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/ec.isfcr.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer0.ec.isfcr.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-ec -M "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer0.ec.isfcr.com/tls" --enrollment.profile tls --csr.hosts peer0.ec.isfcr.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer0.ec.isfcr.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer0.ec.isfcr.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer0.ec.isfcr.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer0.ec.isfcr.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer0.ec.isfcr.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer0.ec.isfcr.com/tls/server.key"


  infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8054 --caname ca-ec -M "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer1.ec.isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/ec.isfcr.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer1.ec.isfcr.com/msp/config.yaml"

  infoln "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8054 --caname ca-ec -M "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer1.ec.isfcr.com/tls" --enrollment.profile tls --csr.hosts peer1.ec.isfcr.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer1.ec.isfcr.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer1.ec.isfcr.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer1.ec.isfcr.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer1.ec.isfcr.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer1.ec.isfcr.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/ec.isfcr.com/peers/peer1.ec.isfcr.com/tls/server.key"


  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-ec -M "${PWD}/organizations/peerOrganizations/ec.isfcr.com/users/User1@ec.isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/ec.isfcr.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/ec.isfcr.com/users/User1@ec.isfcr.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://ecadmin:ecadminpw@localhost:8054 --caname ca-ec -M "${PWD}/organizations/peerOrganizations/ec.isfcr.com/users/Admin@ec.isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ec/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/ec.isfcr.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/ec.isfcr.com/users/Admin@ec.isfcr.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  infoln "mkdiring the folder"
  mkdir -p organizations/ordererOrganizations/isfcr.com
  infoln "mkdir done"

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/isfcr.com



  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/orderer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/isfcr.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/isfcr.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/orderer/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/isfcr.com/msp/tlscacerts/tlsca.isfcr.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/isfcr.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/orderer/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/isfcr.com/tlsca/tlsca.isfcr.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/orderer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/orderer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orderer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/isfcr.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/tls" --enrollment.profile tls --csr.hosts orderer.isfcr.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/orderer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/isfcr.com/orderers/orderer.isfcr.com/msp/tlscacerts/tlsca.isfcr.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/isfcr.com/users/Admin@isfcr.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orderer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/isfcr.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/isfcr.com/users/Admin@isfcr.com/msp/config.yaml"
}
